# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: AzureCI
- group: AzureCI2

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Building container.."
    docker build -t registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:${{ AzureCI2.CI_PIPELINE_IID }} .
    docker login registry.gcp0001.us-east4.astronomer.io -u _ -p ${{ AzureCI.SERVICE-ACCOUNT-KEY }}
    docker push registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:${{ AzureCI2.CI_PIPELINE_IID }}
